import PDFDocument from "pdfkit";

export const generatePdf = async (data) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margin: 50,
        info: {
          Author: "NexusAI",
          Title: data.title || "NexusAI Document",
          Creator: "NexusAI",
        },
      });

      const chunks = [];

      // Collect PDF data
      doc.on("data", (chunk) => {
        chunks.push(chunk);
      });

      // PDF generation completed
      doc.on("end", () => {
        const pdfBuffer = Buffer.concat(chunks);
        resolve(pdfBuffer);
      });

      // PDF generation error
      doc.on("error", (error) => {
        reject(error);
      });

      // Title
      doc
        .fontSize(24)
        .font("Helvetica-Bold")
        .text(data.title || "NexusAI Document", {
          align: "center",
        });

      doc.moveDown(0.5);

      // Subtitle
      if (data.subtitle) {
        doc
          .fontSize(12)
          .font("Helvetica")
          .fillColor("#666666")
          .text(data.subtitle, {
            align: "center",
          });
      }

      doc.moveDown(1.5);

      // Sections
      if (Array.isArray(data.sections)) {
        data.sections.forEach((section, index) => {
          // Section heading
          doc
            .fillColor("#000000")
            .fontSize(16)
            .font("Helvetica-Bold")
            .text(`${index + 1}. ${section.heading || "Section"}`);

          doc.moveDown(0.4);

          // Section points
          if (Array.isArray(section.points)) {
            section.points.forEach((point) => {
              doc
                .fontSize(11)
                .font("Helvetica")
                .fillColor("#222222")
                .text(`• ${point}`, {
                  indent: 15,
                  paragraphGap: 5,
                });
            });
          }

          doc.moveDown(0.8);
        });
      }

      // Footer
      doc
        .fontSize(9)
        .fillColor("#888888")
        .text("Generated by NexusAI", 50, 770, {
          align: "center",
        });

      // Finish PDF
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

export default generatePdf;
